### ISSUE TITLE
Massive stuttering on the pack

### ISSUE THREAD

**Issue by electronic-van** [DabbingEevee/TSMP_Modded_Season_II#20]
I get pretty high fps usually (like 120ish) but there's constant dips down to about 30.
![image](https://user-images.githubusercontent.com/66646659/103564957-4a05d080-4e74-11eb-92b7-25f61f7ae8d8.png)

**Comment by DabbingEevee** [comment]
not sure whats causing this. its probally chunk loading which is now fixed
